"""
Financial Fraud Risk & Exposure Calculation Engine for SENTRY.
Quantifies monetary exposure, expected fraud loss, and avoided fraud value.
"""

from typing import Dict, Any, Optional
import numpy as np


class FinancialRiskEngine:
    """Calculates transactional monetary exposure and avoided loss metrics."""

    def __init__(self, baseline_fraud_prob: float = 0.08, sentry_detection_efficacy: float = 0.85):
        self.baseline_fraud_prob = baseline_fraud_prob
        self.sentry_detection_efficacy = sentry_detection_efficacy

    def format_inr(self, amount: float) -> str:
        """Formats INR amount into readable Indian notation (Lakhs / Crores)."""
        if amount >= 10000000:  # 1 Crore = 10,000,000
            return f"₹{amount / 10000000:.2f} Cr"
        elif amount >= 100000:  # 1 Lakh = 100,000
            return f"₹{amount / 100000:.2f} Lakh"
        elif amount >= 1000:
            return f"₹{amount / 1000:.1f}k"
        else:
            return f"₹{amount:.0f}"

    def compute_transaction_exposure(
        self,
        transaction_amount_inr: float,
        synthetic_prob: float,
        overall_risk_score: float
    ) -> Dict[str, Any]:
        """
        Calculates expected loss before SENTRY, residual loss after SENTRY,
        and estimated exposure avoided for a single interaction.
        """
        amount = max(transaction_amount_inr, 0.0)

        # Baseline expected fraud loss (without real-time voice defense)
        # Expected Loss = P(Fraud) * Exposure
        effective_fraud_prob = float(np.clip(self.baseline_fraud_prob * (1.0 + synthetic_prob * 10.0), 0.01, 0.98))
        expected_loss_baseline = amount * effective_fraud_prob

        # Post-SENTRY: System flags or freezes transaction with high efficacy
        residual_fraud_prob = effective_fraud_prob * (1.0 - self.sentry_detection_efficacy * (overall_risk_score / 100.0))
        residual_loss = amount * residual_fraud_prob

        # Estimated exposure avoided (monetary savings generated by SENTRY)
        avoided_exposure = max(expected_loss_baseline - residual_loss, 0.0)

        return {
            "transaction_amount_inr": amount,
            "formatted_amount": self.format_inr(amount),
            "expected_loss_baseline_inr": round(expected_loss_baseline, 2),
            "formatted_expected_loss": self.format_inr(expected_loss_baseline),
            "residual_loss_inr": round(residual_loss, 2),
            "formatted_residual_loss": self.format_inr(residual_loss),
            "avoided_exposure_inr": round(avoided_exposure, 2),
            "formatted_avoided_exposure": self.format_inr(avoided_exposure),
            "effective_fraud_probability_pct": round(effective_fraud_prob * 100.0, 1),
            "residual_probability_pct": round(residual_fraud_prob * 100.0, 1)
        }


financial_engine = FinancialRiskEngine()
